tasks:
  - task_type: semantic_segmentation
    models:
      - model_name: FCN_ResNet101
        load_model:
          _target_: src.load_models.load_model
          model_loading_function: torchvision.models.segmentation.fcn_resnet101
          weights: torchvision.models.segmentation.FCN_ResNet101_Weights
          weight_version: DEFAULT
        inference:
          framework: torch
          unsqueeze: true
          to_tensor: true
        postprocessing:
          tracker: true
  - task_type: keypoints
    models:
      - model_name: KeypointRCNN_ResNet50
        load_model:
          _target_: src.load_models.load_model
          model_loading_function: torchvision.models.detection.keypointrcnn_resnet50_fpn
          weights: torchvision.models.detection.KeypointRCNN_ResNet50_FPN_Weights
          weight_version: DEFAULT
        inference:
          framework: torch
          unsqueeze: false
          to_tensor: false
        postprocessing:
          tracker: true
inputs:
  path: /tank/tgn252/vid_folder
output:
  path: /tank/tgn252/metadata_annotations/results